// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCC-nDZrXnb_eoT35SDervz1XNLL2HJrHI',
    appId: '1:362615523483:web:9e4e48afbf0b1546149e3e',
    messagingSenderId: '362615523483',
    projectId: 'my-chats-f8d4e',
    authDomain: 'my-chats-f8d4e.firebaseapp.com',
    storageBucket: 'my-chats-f8d4e.firebasestorage.app',
    measurementId: 'G-9G5XZ63CM1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFQiJIaslEXv7kO3wrjaDscAecuGifwb8',
    appId: '1:362615523483:android:f5cb157da8a893f1149e3e',
    messagingSenderId: '362615523483',
    projectId: 'my-chats-f8d4e',
    storageBucket: 'my-chats-f8d4e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqTSyeAXZqoGWPgwwuapyV9XUucGvXGDo',
    appId: '1:362615523483:ios:eecbbef9d5273251149e3e',
    messagingSenderId: '362615523483',
    projectId: 'my-chats-f8d4e',
    storageBucket: 'my-chats-f8d4e.firebasestorage.app',
    iosBundleId: 'com.example.myChats',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqTSyeAXZqoGWPgwwuapyV9XUucGvXGDo',
    appId: '1:362615523483:ios:eecbbef9d5273251149e3e',
    messagingSenderId: '362615523483',
    projectId: 'my-chats-f8d4e',
    storageBucket: 'my-chats-f8d4e.firebasestorage.app',
    iosBundleId: 'com.example.myChats',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCC-nDZrXnb_eoT35SDervz1XNLL2HJrHI',
    appId: '1:362615523483:web:4708335d5cf4e386149e3e',
    messagingSenderId: '362615523483',
    projectId: 'my-chats-f8d4e',
    authDomain: 'my-chats-f8d4e.firebaseapp.com',
    storageBucket: 'my-chats-f8d4e.firebasestorage.app',
    measurementId: 'G-5555F1L2SZ',
  );
}
